### ISSUE TITLE
Rewrite the documentation of standard functions

### ISSUE THREAD

**Issue by 99NIMI** [PLC-lang/StandardFunctions#42]
we should add more information for the functions, description, inputs, outputs, return ....
e.g M200 documentation of SR
```
(******************************************************************************
Description: Bistable function, set dominant
Input:
  - SET1: Dominant input of bistable function.
  - RESET: input of bistable function.
Output:
  - Q1: Result of Bistable function. 
Return: Output is used as return
******************************************************************************)
```
